### ISSUE TITLE
Error running test same-live.sh

### ISSUE THREAD

**Issue by fdns** [dns-stats/compactor#28]
Hello, I'm compiling compactor from source (tag 0.11.0), and I have the following error when I run the tests.
```
===================================================
   dns-stats-compactor 0.1-dev: ./test-suite.log
===================================================

# TOTAL: 18
# PASS:  16
# SKIP:  1
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-scripts/same-live.sh
===============================

Wrong number of errors: 0 != 6
Checking knot-live failed.
FAIL test-scripts/same-live.sh (exit status: 1)

SKIP: test-scripts/verify-cddl.sh
=================================

No cddl, skipping test.
SKIP test-scripts/verify-cddl.sh (exit status: 77)
```

I'm using boost-1.66, libtins-3.5 and libpcap-1.8.1.

**Comment by banburybill** [comment]
This is almost certainly an issue with the version of libtins; however, libtins 3.5 should be OK. I will investigate.

**Comment by banburybill** [comment]
I've built and run the test suite against libtins-3.5. For me, everything passes.

The test failure you describe is typically due to using libtins-3.4, which requires a small patch to fix a typo in the TCP streams code - hence the patched Ubuntu packages for libtins in the compactor PPA https://launchpad.net/~dns-stats/+archive/ubuntu/compactor. Are you sure you're not picking up a system libtins-3.4 somewhere?

I also found that compiling fails with libtins-4.0. I'll note this as an issue.

PASS: compactor-tests
PASS: test-scripts/check-config-info.sh
PASS: test-scripts/check-outputs.sh
PASS: test-scripts/check-testcontent.sh
PASS: test-scripts/inspector-outputs.sh
PASS: test-scripts/same-output.sh
PASS: test-scripts/same-output-gzip.sh
PASS: test-scripts/same-output-xz.sh
PASS: test-scripts/same-file-output.sh
PASS: test-scripts/same-pcap-cbor-pcap.sh
PASS: test-scripts/same-qr-dump.sh
PASS: test-scripts/tmp-output.sh
PASS: test-scripts/same-tshark-output.sh
PASS: test-scripts/same-live.sh
PASS: test-scripts/verify-cbor02.sh
PASS: test-scripts/verify-cddl.sh
PASS: test-scripts/pseudoanon-tshark-output.sh
PASS: test-scripts/pseudoanon-inspector-output.sh
============================================================================
Testsuite summary for dns-stats-compactor 0.11.0
============================================================================
# TOTAL: 18
# PASS:  18
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

**Comment by fdns** [comment]
I compiled libtins-v3.5 from source, so I'm sure its the correct version (I don't have any other installed). I also tried v3.4 and got another error.

I will look into it, but if it works for you maybe I'm missing something. You can close this if you can't reproduce the error.

**Comment by fdns** [comment]
I found the issue, the file test-scripts/check-live-pcap.sh is using a fixed "/usr/sbin/tcpdump", and its not showing any error if the binary is not found. Maybe adding a check like in verify-cddl.sh can prevent this issue in the future.
Thanks for your help.

**Comment by banburybill** [comment]
OK, thanks for letting me know. I'm reopening the issue and will fix as you suggest - and also some similar potential problems.

Out of interest, was it just your system did not have tcpdump installed, or is it installed on a different path? We're building compactor on our internal Jenkins on Ubuntu, Mac and FreeBSD, and had not hit this problem to date.

**Comment by fdns** [comment]
I'm building compactor on a NixOS system (I was planning to send it upstream), so I had to declare all the dependencies. It also mean that all the binaries are on a different path, so some light patches were needed (some hardcoded paths in the tests).

Here is the file I use to build the project (pretty easy to read), it could help to document the dependencies to run/test the project.
https://github.com/fdns/nixpkgs/blob/4dcea993a9c36d47255c3869e9a6e00c1bcb5201/pkgs/applications/networking/compactor/default.nix

PD: I tested the fix, and same-live.sh always passed the check (no SKIP) even without the dependency. I checked and it was because an extra space storing the return code, I submitted #30 with the short fix. The other tests worked correctly when I removed cddl and the wireshark commands.
PD2: It seems that the author of the cddl tool removed his github project, and only the rubygem remains.
